import { bottomType } from '../models/superIndex'

export const bottomData:bottomType[]=[
  {
    icon:"/images/tabBarIco/index.png",
    selectedIcon:"/images/tabBarIco/index_sel.png",
    name:"首页",
    url:"pages/superIndex"
  },
  {
    icon:"/images/tabBarIco/search.png",
    selectedIcon:"/images/tabBarIco/search_sel.png",
    name:"搜索",
    url:"pages/superSearch"
  },
  {
    icon:"/images/tabBarIco/me.png",
    selectedIcon:"/images/tabBarIco/me_sel.png",
    name:"我的",
    url:"pages/superMy"
  },

]